# -*- coding: utf-8 -*-
"""FineTuneAModel-LoRA-PEFT.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1i9fr2yHJ3EtZ-YYwlLYMvA3RZ3sEv6Nz

### **Installs and Imports**
"""

!pip install -q transformers datasets peft trl

# Upgrade torchao to a compatible version
!pip install --upgrade torchao

import torch, random
import requests
from transformers import AutoModelForCausalLM, AutoTokenizer
from peft import LoraConfig, get_peft_model, PeftModel
from datasets import load_dataset
from trl import DPOTrainer, DPOConfig

"""### **Load the base model** and tokenizer, put the model on the GPU."""

model_id = "HuggingFaceTB/SmolLM-135M"     # BASE, not -Instruct

device    = 'cuda' if torch.cuda.is_available() else 'cpu'
tokenizer = AutoTokenizer.from_pretrained(model_id)
model     = AutoModelForCausalLM.from_pretrained(model_id).to(device)

print(f"Loaded {model_id} on {device} — {sum(p.numel() for p in model.parameters()):,} params")

"""### **Wrap the Model with LoRA Adapters:**"""

lora_config = LoraConfig(
    task_type      = "CAUSAL_LM",                # tells peft this is a next-token LM
    r              = 8,                          # the rank — size of A and B
    lora_alpha     = 16,                         # scaling: effective ΔW = (alpha/r)·B·A
    target_modules = ["q_proj", "v_proj"],       # WHICH layers get adapters
    lora_dropout   = 0.05,                       # dropout on the adapter path
    bias           = "none",                     # don't train bias terms
)

model = get_peft_model(model, lora_config)
model.print_trainable_parameters()

"""### **CPT-LoRA** using HuggingFace wikitext-dataset:"""

ds = load_dataset("Salesforce/wikitext", "wikitext-2-raw-v1")

# CPT = raw text, every token counts. Join non-empty lines into one corpus.
train_text = "\n".join(t for t in ds["train"]["text"]      if t.strip())
val_text   = "\n".join(t for t in ds["validation"]["text"] if t.strip())

# Pack into one flat stream — exactly your Shakespeare CPT prep, new source
train_ids = torch.tensor(tokenizer(train_text, add_special_tokens=False)["input_ids"])
val_ids   = torch.tensor(tokenizer(val_text,   add_special_tokens=False)["input_ids"])
print(f"train tokens: {len(train_ids):,} | val tokens: {len(val_ids):,}")

"""### **Hyperparameters + The Batch Loader:**"""

block_size, batch_size = 256, 8
lr, weight_decay, grad_clip = 2e-4, 0.01, 1.0
max_steps, eval_every = 500, 50

def get_batch(split):
    d  = train_ids if split == "train" else val_ids
    ix = torch.randint(len(d) - block_size, (batch_size,))
    xb = torch.stack([d[i:i+block_size] for i in ix])
    return xb.to(device)

"""### **Optimizer** + fixed held-out eval:"""

optimizer = torch.optim.AdamW(model.parameters(), lr=lr, weight_decay=weight_decay)

@torch.no_grad()
def estimate_loss(batches=20):
    model.eval()
    total = 0.0
    for _ in range(batches):
        xb = get_batch("val")
        total += model(input_ids=xb, labels=xb).loss.item()
    model.train()
    return total / batches

"""### **Training loop:**"""

model.train()
for step in range(max_steps):
    xb   = get_batch("train")
    loss = model(input_ids=xb, labels=xb).loss

    optimizer.zero_grad()
    loss.backward()
    torch.nn.utils.clip_grad_norm_(model.parameters(), grad_clip)
    optimizer.step()

    if step % eval_every == 0 or step == max_steps - 1:
        print(f"step {step:4d} | train {loss.item():.4f} | val {estimate_loss():.4f}")

"""### **Generate:**"""

def sample(prompt, max_new_tokens=120):
    model.eval()
    enc = tokenizer(prompt, return_tensors="pt").to(device)
    out = model.generate(**enc, max_new_tokens=max_new_tokens, do_sample=True,
                         temperature=0.7, top_p=0.9, repetition_penalty=1.3,
                         no_repeat_ngram_size=3, pad_token_id=tokenizer.eos_token_id)
    return tokenizer.decode(out[0], skip_special_tokens=True)

print(sample("The history of the Roman Empire"))

"""### Before **LoRA-CPT**:

The history of the Roman Empire began in 286 BC, when a large group of people from what is now Turkey were expelled by the Romans. They settled around the city of Rome and became known as the "Romans". The Romans had many different cultures that influenced their way of life - Greek culture was very important to them because it helped shape how they saw themselves today!
One interesting thing about the Romans' relationship with other ancient civilizations like Greece comes up again: there are some similarities between these two groups but also lots more differences too (like language). For example; while Greeks spoke Latin instead of Ancient Greek due its

### After **LoRA-CPT**:

The history of the Roman Empire is a fascinating one. It was not only an empire , it also had its own distinct culture . The Romans were very successful in their conquest and rule over much of Europe until they fell under the power of Germanic tribes at the end of the 5th century AD ; however , as well as some of the smaller empires which arose around this time such as the Byzantine Empire ( which included parts of what are now Turkey, Greece and Bulgaria ) , there has been little historical research on the Romans themselves during this period - despite being thought to have originated from the Roman city of Aquileia in Italy where

### **Save The Model Adapters:**
"""

model.save_pretrained("smollm-lora-cpt-wikitext")   # saves ONLY the adapters — a few MB, not 500MB

"""---

## **LoRA-SFT** using Alpaca Datset from HuggingFace:

---

### **Reload and add the adapters:**
"""

base  = AutoModelForCausalLM.from_pretrained("HuggingFaceTB/SmolLM-135M").to(device)
model = PeftModel.from_pretrained(base, "smollm-lora-cpt-wikitext", is_trainable=True).to(device)
model.print_trainable_parameters()   # should say ~460,800 trainable — NOT 0

"""### **Load Dataset** (load + format the SFT data (instruction/response pairs)):"""

ds = load_dataset("tatsu-lab/alpaca")          # only a 'train' split exists

def format_pair(row):
    instr, inp, out = row["instruction"], row["input"], row["output"]
    if inp.strip():                            # ~40% of rows carry an 'input'
        prompt = f"### Instruction:\n{instr}\n\n### Input:\n{inp}\n\n### Response:\n"
    else:
        prompt = f"### Instruction:\n{instr}\n\n### Response:\n"
    return prompt, out

all_pairs = [format_pair(r) for r in ds["train"].select(range(3000))]
random.shuffle(all_pairs)
train_pairs, val_pairs = all_pairs[:2700], all_pairs[2700:]   # our own held-out split
print(f"train pairs: {len(train_pairs)} | val pairs: {len(val_pairs)}")

"""### **Hyperparameters:**"""

EOS = tokenizer.eos_token_id
PAD = tokenizer.pad_token_id
if PAD is None:                              # SmolLM base tokenizer has no pad token
    tokenizer.pad_token = tokenizer.eos_token
    PAD = tokenizer.eos_token_id             # reuse EOS as the pad id
assert EOS is not None and PAD is not None, (EOS, PAD)
print("EOS:", EOS, "| PAD:", PAD)            # confirm both are real ints

MAX_LEN   = 512
batch_sz  = 4
lr, weight_decay, grad_clip = 2e-4, 0.01, 1.0
max_steps, eval_every = 500, 50

"""### **Masked-example Builder:**"""

def build_example(prompt_text, response_text):
    p = tokenizer(prompt_text,   add_special_tokens=False)["input_ids"]
    r = tokenizer(response_text, add_special_tokens=False)["input_ids"] + [EOS]
    input_ids = (p + r)[:MAX_LEN]
    labels    = ([-100]*len(p) + r)[:MAX_LEN]      # mask prompt → loss only on response
    return input_ids, labels

"""### **Collate SFT Batches (Packing) and Batch-Loader:**"""

def collate(batch_pairs):
    ex = [build_example(p, r) for p, r in batch_pairs]
    maxlen = max(len(ids) for ids, _ in ex)
    input_ids, labels, attn = [], [], []
    for ids, lab in ex:
        pad = maxlen - len(ids)
        input_ids.append(ids + [PAD]  * pad)
        labels.append(   lab + [-100] * pad)       # padding never contributes
        attn.append(     [1]*len(ids) + [0]*pad)   # padding mask
    t = lambda z: torch.tensor(z).to(device)
    return t(input_ids), t(labels), t(attn)

def get_sft_batch(pool):
    return collate(random.sample(pool, batch_sz))

"""### **Optimizer + Fixed held-out Eval:**"""

optimizer = torch.optim.AdamW(model.parameters(), lr=lr, weight_decay=weight_decay)

@torch.no_grad()
def estimate_loss(batches=20):
    model.eval()
    total = 0.0
    for _ in range(batches):
        input_ids, labels, attn = get_sft_batch(val_pairs)
        total += model(input_ids=input_ids, attention_mask=attn, labels=labels).loss.item()
    model.train()
    return total / batches

"""### **Training Loop** (SFT: masked labels + attention_mask):"""

model.train()
for step in range(max_steps):
    input_ids, labels, attn = get_sft_batch(train_pairs)
    loss = model(input_ids=input_ids, attention_mask=attn, labels=labels).loss

    optimizer.zero_grad()
    loss.backward()
    torch.nn.utils.clip_grad_norm_(model.parameters(), grad_clip)
    optimizer.step()

    if step % eval_every == 0 or step == max_steps - 1:
        print(f"step {step:4d} | train {loss.item():.4f} | val {estimate_loss():.4f}")

"""### **Generate:**"""

def sft_generate(instruction, inp=""):
    prompt = (f"### Instruction:\n{instruction}\n\n### Input:\n{inp}\n\n### Response:\n"
              if inp.strip() else
              f"### Instruction:\n{instruction}\n\n### Response:\n")
    model.eval()
    enc = tokenizer(prompt, return_tensors="pt").to(device)
    out = model.generate(**enc, max_new_tokens=150, do_sample=True,
                         temperature=0.7, top_p=0.9, repetition_penalty=1.3,
                         pad_token_id=tokenizer.eos_token_id)
    return tokenizer.decode(out[0][enc["input_ids"].shape[1]:], skip_special_tokens=True)

print(sft_generate("Explain photosynthesis in simple terms."))

"""### **Base Model:**
Photosynthesis occurs when light energy from the sun is absorbed by chlorophyll molecules within plant cells, resulting in a chemical reaction that turns water and carbon dioxide into glucose (a type of sugar) through an electron transfer process called photophosphorylation or chemiosmosis. This unique method allows plants to convert sunlight directly using their own internal capacity for producing ATP—the powerhouse responsible for generating electricity! By doing so efficiently while maintaining stability inside cell walls like those found on leaves; chloroplasts play essential roles during growth cycles involving multiple stages such as germination/ovulation phases followed closely after fertilization until reaching maturity level where reproduction takes place via sexual means including pollination between male and female reproductive organs involved here before releasing fertilized eggs carrying genetic information necessary later forming new individuals


### **After CPT:**
1 . The answer is a true statement

2  In the process of converting sunlight into food through light-dependent reactions , plants use energy from molecules and chemical bonds to convert carbon dioxide ( CO₂ ) present within air or water vapor onto glucose molecule which then can be used as fuel for cellular respiration by living cells

3 . In order to get more oxygen required during combustion, organisms have evolved specialised structures such as leaves that capture solar radiation at night whilst trapping it inside their bodies while allowing animals consuming them access daily without any risk if they were not able to obtain sufficient amounts needed throughout day time when less efficient mechanisms are available like photolysis [ 9 ] / photosynthesis ; these organs enable greater efficiency towards obtaining O₃ gas necessary via chem



### **After SFT:**
Photosynthesis is the process by which plants and other photosynthetic organisms convert light energy into chemical potential from water to produce glucose (sugar) as a source of fuel for growth, development ,and maintenance .

### **Save The Adapters:**
"""

model.save_pretrained("smollm-lora-sft-alpaca")

"""---

## **RLHF + DPO (Direct Preference Optimization)**

---

### **Rebuild the SFT'd model and MERGE the SFT adapters into the base:**

`merge_and_unload` computes `W' = W + (alpha/r)·B·A` for every adapted layer and returns a plain model with no LoRA machinery left.
"""

base  = AutoModelForCausalLM.from_pretrained("HuggingFaceTB/SmolLM-135M").to(device)
sft   = PeftModel.from_pretrained(base, "smollm-lora-sft-alpaca")   # reattach SFT adapters
model = sft.merge_and_unload()                                      # fold W + (α/r)·B·A → W
# `model` is now an ORDINARY CausalLM whose weights ARE the SFT'd SmolLM

"""### **Load + Format the preference dataset** (standard prompt/chosen/rejected):"""

TEMPLATE = "### Instruction:\n{instruction}\n\n### Response:\n"   # SAME template as SFT

raw = load_dataset("Intel/orca_dpo_pairs", split="train")
print(raw[0].keys())   # dict_keys(['system', 'question', 'chosen', 'rejected'])

def to_pref(row):
    return {
        "prompt":   TEMPLATE.format(instruction=row["question"]),
        "chosen":   row["chosen"],
        "rejected": row["rejected"],
    }

pref = raw.map(to_pref, remove_columns=raw.column_names).select(range(2000))
print(pref[0]["prompt"][:120])
print("CHOSEN  :", pref[0]["chosen"][:80])
print("REJECTED:", pref[0]["rejected"][:80])

"""### **LoRA config for the DPO stage + The DPO Hyperparameters:**"""

peft_config = LoraConfig(
    task_type="CAUSAL_LM", r=8, lora_alpha=16,
    target_modules=["q_proj", "v_proj"], lora_dropout=0.05, bias="none",
)

dpo_config = DPOConfig(
    output_dir                  = "smollm-dpo-orca",
    beta                        = 0.1,        # β — the KL-leash strength from the DPO loss
    learning_rate               = 5e-6,       # tiny, for the reasons from last session
    per_device_train_batch_size = 2,
    gradient_accumulation_steps = 4,          # effective batch = 2 × 4 = 8
    num_train_epochs            = 1,
    max_steps                   = 300,        # cap for a fast Colab run
    max_length                  = 1024,
    warmup_steps                = 0.1,
    lr_scheduler_type           = "cosine",
    logging_steps               = 20,
    bf16                        = torch.cuda.is_available(),
    report_to                   = "none",
)

"""### **Build the DPOTrainer and Train:**"""

trainer = DPOTrainer(
    model           = model,          # the merged SFT model (plain CausalLM)
    ref_model       = None,           # None → reference = this model with the DPO adapter DISABLED
    args            = dpo_config,
    train_dataset   = pref,
    processing_class= tokenizer,      # TRL's current name for the tokenizer argument
    peft_config     = peft_config,    # fresh adapters, added on top of the merged SFT base
)
trainer.train()

"""### **Show Log History:**"""

import pandas as pd
logs = pd.DataFrame(trainer.state.log_history)
cols = [c for c in ["step","loss","rewards/accuracies","rewards/margins",
                    "rewards/chosen","rewards/rejected"] if c in logs]
print(logs[cols].dropna().to_string(index=False))

"""### **Save the DPO adapter:**"""

trainer.save_model("smollm-dpo-orca")

"""### **Generate & Compare:**"""

def compare(instruction, max_new_tokens=150, seed=0):
    prompt = TEMPLATE.format(instruction=instruction)
    enc = tokenizer(prompt, return_tensors="pt").to(device)
    m = trainer.model; m.eval()
    kw = dict(max_new_tokens=max_new_tokens, do_sample=True, temperature=0.7,
              top_p=0.9, repetition_penalty=1.3, pad_token_id=tokenizer.eos_token_id)
    strip = lambda o: tokenizer.decode(o[0][enc["input_ids"].shape[1]:], skip_special_tokens=True)

    torch.manual_seed(seed)                          # same random draw for a fair A/B
    with torch.no_grad(), m.disable_adapter():       # DPO adapter OFF → SFT model
        before = strip(m.generate(**enc, **kw))

    torch.manual_seed(seed)                          # reseed → identical sampling stream
    with torch.no_grad():                            # DPO adapter ON → aligned model
        after = strip(m.generate(**enc, **kw))

    print("PROMPT:", instruction)
    print("\n── SFT (adapter OFF, before DPO) ──\n", before)
    print("\n── DPO (adapter ON, after) ──\n", after)

compare("Explain why the sky is blue.")

"""### **PROMPT**: Explain why the sky is blue.

### ── **SFT (adapter OFF, before DPO)** ──
 The reason for the color of skies and sunsets being a beautiful shade that we see during sunset or sunrise, as opposed to other colors such as red because it takes longer time than in winter due to its higher temperature level which makes us perceive more blues from this perspective

### ── **DPO (adapter ON, after)** ──
 The reason for the color of skies being seen as they appear to be clear and bluish due to low atmospheric concentrations, which results in a decrease in red light intensity over time because it takes longer at higher altitudes than lower latitudes such as Antarctica or high mountains where sunlight can reach more directly through clouds that are visible from above them (a phenomenon known as the albedo effect).

"""